allowBuilds:
  '@parcel/watcher': set this to true or false
  '@swc/core': set this to true or false
  msw: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
