import { cn } from "@/lib/utils";
import { Component } from "@/type/component";
import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import Image from "next/image";
import { PropsWithChildren } from "react";
import "./globals.css";

const outfit = Outfit({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-outfit",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: Component<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="en">
      <body className={`${outfit.className} antialiased bg-[#121212] text-white relative min-h-screen`}>
        <div className="absolute top-0 left-0 right-0 overflow-hidden pointer-events-none">
          <div className="w-full h-96">
            <Image 
              src="/BWR.webp" 
              alt="BWR" 
              width={1000}
              height={256}
              className="w-full h-full"
            />
          </div>
        </div>
        
        <div className={cn(
          "relative z-10",
          "p-4 sm:p-6 md:p-8 lg:p-10 xl:p-12 2xl:p-16",
          "max-w-4xl mx-auto"
        )}>
          {children}
        </div>
      </body>
    </html>
  );
}

export default RootLayout;