import type { Skill } from "./skills.types";

export const Typescript: Skill = { name: "TypeScript", icon: "typescript" };
export const Javascript: Skill = { name: "JavaScript", icon: "javascript" };
export const Html: Skill = { name: "HTML", icon: "html" };
export const Css: Skill = { name: "CSS", icon: "css" };
export const Sass: Skill = { name: "SASS", icon: "sass" };
export const Tailwindcss: Skill = { name: "TailwindCSS", icon: "tailwindcss" };
export const Svelte: Skill = { name: "Svelte", icon: "svelte" };
export const Php: Skill = { name: "PHP", icon: "php" };
export const Vercel: Skill = { name: "Vercel", icon: "vercel" };
export const Railway: Skill = { name: "Railway", icon: "railway" };
export const Supabase: Skill = { name: "Supabase", icon: "supabase" };
export const Postgresql: Skill = { name: "PostgreSQL", icon: "postgresql" };
export const Mysql: Skill = { name: "MySQL", icon: "mysql" };
export const MongoDb: Skill = { name: "MongoDB", icon: "mongodb" };
export const Redis: Skill = { name: "Redis", icon: "redis" };
export const Docker: Skill = { name: "Docker", icon: "docker" };
export const Git: Skill = { name: "Git", icon: "git" };
export const Github: Skill = { name: "GitHub", icon: "github" };
export const Graphql: Skill = { name: "GraphQL", icon: "graphql" };
export const Firebase: Skill = { name: "Firebase", icon: "firebase" };
export const Nodejs: Skill = { name: "NodeJS", icon: "nodejs" };
export const Fastify: Skill = { name: "Fastify", icon: "fastify" };
export const Java: Skill = { name: "Java", icon: "java" };
export const DiscordJs: Skill = { name: "DiscordJS", icon: "discordjs" };
export const Prisma: Skill = { name: "Prisma", icon: "prisma" };
export const OpenAI: Skill = { name: "OpenAI", icon: "openai" };