import type { Skill } from "./skills.types";

export const Typescript: Skill = { name: "TypeScript", icon: "typescript", color: "#3178C6" };
export const Javascript: Skill = { name: "JavaScript", icon: "javascript", color: "#F7DF1E" };
export const Html: Skill = { name: "HTML", icon: "html", color: "#E34F26" };
export const Css: Skill = { name: "CSS", icon: "css", color: "#1572B6" };
export const Sass: Skill = { name: "SASS", icon: "sass", color: "#CC6699" };
export const Tailwindcss: Skill = { name: "TailwindCSS", icon: "tailwindcss", color: "#38B2AC" };
export const Svelte: Skill = { name: "Svelte", icon: "svelte", color: "#FF3E00" };
export const Php: Skill = { name: "PHP", icon: "php", color: "#777BB4" };
export const Vercel: Skill = { name: "Vercel", icon: "vercel", color: "#000000" };
export const Railway: Skill = { name: "Railway", icon: "railway", color: "#000000" };
export const Supabase: Skill = { name: "Supabase", icon: "supabase", color: "#49d633" };
export const Postgresql: Skill = { name: "PostgreSQL", icon: "postgresql", color: "#336791" };
export const Mysql: Skill = { name: "MySQL", icon: "mysql", color: "#4479A1" };
export const MongoDb: Skill = { name: "MongoDB", icon: "mongodb", color: "#47A248" };
export const Redis: Skill = { name: "Redis", icon: "redis", color: "#DC382D" };
export const Docker: Skill = { name: "Docker", icon: "docker", color: "#2496ED" };
export const Git: Skill = { name: "Git", icon: "git", color: "#F05032" };
export const Github: Skill = { name: "GitHub", icon: "github", color: "#181717" };
export const Graphql: Skill = { name: "GraphQL", icon: "graphql", color: "#E10098" };
export const Firebase: Skill = { name: "Firebase", icon: "firebase", color: "#FFCA28" };
export const Nodejs: Skill = { name: "NodeJS", icon: "nodejs", color: "#339933" };
export const Fastify: Skill = { name: "Fastify", icon: "fastify", color: "#503E33" };
export const Java: Skill = { name: "Java", icon: "java", color: "#007396" };
export const DiscordJs: Skill = { name: "DiscordJS", icon: "discordjs", color: "#7289DA" };
export const Prisma: Skill = { name: "Prisma", icon: "prisma", color: "#0C344B" };
export const OpenAI: Skill = { name: "OpenAI", icon: "openai", color: "#74AA9C" };