import type { Skill } from "./skills.types";

export const Typescript: Skill = { name: "TypeScript", icon: "typescript", link: "https://typescriptlang.org" };
export const Javascript: Skill = { name: "JavaScript", icon: "javascript", link: "https://javascript.com" };
export const Tailwindcss: Skill = { name: "TailwindCSS", icon: "tailwindcss", link: "https://tailwindcss.com" };
export const Svelte: Skill = { name: "Svelte", icon: "svelte", link: "https://svelte.dev" };
export const Php: Skill = { name: "PHP", icon: "php", link: "https://php.net" };
export const Vercel: Skill = { name: "Vercel", icon: "vercel", link: "https://vercel.com" };
export const Railway: Skill = { name: "Railway", icon: "railway", link: "https://railway.app" };
export const Supabase: Skill = { name: "Supabase", icon: "supabase", link: "https://supabase.com" };
export const Postgresql: Skill = { name: "PostgreSQL", icon: "postgresql", link: "https://postgresql.org" };
export const Mysql: Skill = { name: "MySQL", icon: "mysql", link: "https://mysql.com" };
export const MongoDb: Skill = { name: "MongoDB", icon: "mongodb", link: "https://mongodb.com" };
export const Redis: Skill = { name: "Redis", icon: "redis", link: "https://redis.io" };
export const Docker: Skill = { name: "Docker", icon: "docker", link: "https://docker.com" };
export const Git: Skill = { name: "Git", icon: "git", link: "https://git-scm.com" };
export const Github: Skill = { name: "GitHub", icon: "github", link: "https://github.com" };
export const Graphql: Skill = { name: "GraphQL", icon: "graphql", link: "https://graphql.org" };
export const Nodejs: Skill = { name: "NodeJS", icon: "nodejs", link: "https://nodejs.org" };
export const Fastify: Skill = { name: "Fastify", icon: "fastify", link: "https://fastify.io" };
export const Express: Skill = { name: "Express", icon: "express", link: "https://expressjs.com" };
export const Java: Skill = { name: "Java", icon: "java", link: "https://java.com" };
export const DiscordJs: Skill = { name: "DiscordJS", icon: "discordjs", link: "https://discord.js.org" };
export const Prisma: Skill = { name: "Prisma", icon: "prisma", link: "https://prisma.io" };
export const OpenAI: Skill = { name: "OpenAI", icon: "openai", link: "https://openai.com" };
export const Google: Skill = { name: "PSE", icon: "google", link: "https://developers.google.com/custom-search/v1/overview" };